import { format } from 'prettier'

import type { AgentConfig, Outline } from '../types.js'

function parseRepo(full: string): { owner: string; repo: string } {
  const parts = full.trim().split('/')
  const owner = parts[0]
  const repo = parts[1]
  if (parts.length !== 2 || !owner || !repo) {
    throw new Error(`Invalid githubRepo "${full}" (expected owner/repo)`)
  }
  return { owner, repo }
}

function safeRefSegment(slug: string): string {
  return (
    slug
      .replace(/[^a-z0-9-]/gi, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') || 'draft'
  )
}

function draftMarkdown(outline: Outline): string {
  const desc = outline.summary.replace(/\s+/g, ' ').trim().replace(/'/g, "''")
  const title = outline.title.replace(/'/g, "''")
  const src = outline.sourceUrl.replace(/'/g, "''")
  const sections = outline.sections.map((s, i) => `## Section ${i + 1}: ${s}`).join('\n\n')
  return `---
title: '${title}'
description: '${desc}'
date: '${outline.date}'
author: 'Multicorn Team'
tags:
  - ai-101
  - news
  - outline
audienceLevel: '${outline.audienceLevel}'
status: 'outline'
sourceUrl: '${src}'
generatedBy: 'multicorn-content'
---

${sections}
`
}

const API = 'https://api.github.com'

/**
 * Creates a branch, commits the draft outline, opens a PR to main.
 */
export async function createDraftPR(outline: Outline, config: AgentConfig): Promise<string> {
  const { owner, repo } = parseRepo(config.githubRepo)
  const token = config.githubToken
  const headers: HeadersInit = {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  }

  const refRes = await fetch(`${API}/repos/${owner}/${repo}/git/ref/heads/main`, {
    headers,
  })
  if (!refRes.ok) {
    const t = await refRes.text()
    throw new Error(`GitHub: could not read main ref (${refRes.status}): ${t.slice(0, 200)}`)
  }
  const refBody = (await refRes.json()) as { object: { sha: string } }
  const mainSha = refBody.object.sha

  const slug = safeRefSegment(outline.slug)
  const branch = `content/${outline.date}-${slug}`
  const path = `drafts/${outline.date}-${slug}.md`
  const raw = draftMarkdown(outline)
  const formatted = await format(raw, { parser: 'markdown', proseWrap: 'always', printWidth: 80 })
  const content = Buffer.from(formatted, 'utf8').toString('base64')

  const createRefRes = await fetch(`${API}/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: mainSha,
    }),
  })
  if (!createRefRes.ok) {
    const t = await createRefRes.text()
    throw new Error(`GitHub: create branch failed (${createRefRes.status}): ${t.slice(0, 200)}`)
  }

  const putRes = await fetch(`${API}/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify({
      message: `content: add draft outline ${outline.slug}`,
      content,
      branch,
    }),
  })
  if (!putRes.ok) {
    const t = await putRes.text()
    throw new Error(`GitHub: commit file failed (${putRes.status}): ${t.slice(0, 200)}`)
  }

  const prRes = await fetch(`${API}/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      title: `Draft outline: ${outline.title}`,
      head: branch,
      base: 'main',
      body:
        `Outline generated by multicorn-content.\n\n` +
        `Source: ${outline.sourceUrl}\n\n` +
        `Audience: ${outline.audienceLevel}`,
    }),
  })
  if (!prRes.ok) {
    const t = await prRes.text()
    throw new Error(`GitHub: open PR failed (${prRes.status}): ${t.slice(0, 200)}`)
  }
  const pr = (await prRes.json()) as { html_url: string }
  return pr.html_url
}
