import type { MetadataRoute } from 'next'

const BASE_URL = 'https://multicorn.ai'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: BASE_URL,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 1,
    },
    {
      url: `${BASE_URL}/shield`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/shield/compare`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE_URL}/shield/threat-model`,
      lastModified: new Date('2026-04-14'),
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE_URL}/learn`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/learn/prompts`,
      lastModified: new Date('2026-04-15'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/pricing`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: `${BASE_URL}/changelog`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/blog/introducing-multicorn-shield`,
      lastModified: new Date('2026-02-20'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/ai-agents-doing-things-nobody-asked`,
      lastModified: new Date('2026-03-12'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/the-agent-did-nothing-wrong`,
      lastModified: new Date('2026-03-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/shield-vs-mj-rathbun`,
      lastModified: new Date('2026-02-11'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/what-your-ai-agent-did`,
      lastModified: new Date('2026-02-12'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/openclaw-permissions-shield`,
      lastModified: new Date('2026-03-04'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/openai-data-agent-what-enterprises-need`,
      lastModified: new Date('2026-03-06'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/rome-agent-crypto-mining-what-it-means`,
      lastModified: new Date('2026-03-09'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/amazon-ai-outage-shield`,
      lastModified: new Date('2026-03-16'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/what-minimax-m27-actually-does`,
      lastModified: new Date('2026-03-20'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/block-ai-layoffs-governance-gap`,
      lastModified: new Date('2026-04-01'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/anthropic-ai-jobs-governance-gap`,
      lastModified: new Date('2026-04-03'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/llm-router-supply-chain-attack`,
      lastModified: new Date('2026-04-11'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/blog/prompts-drift-policies-dont`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/installing-cursor`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/your-first-prompt`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/reading-the-code`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/iterating-on-your-app`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/writing-tests`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/cursor/whats-next`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/installing-claude-code`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/your-first-task`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/file-editing-model`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/using-mcp`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/writing-tests`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/course-2/claude-code/whats-next`,
      lastModified: new Date('2026-04-17'),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101`,
      lastModified: new Date('2026-02-20'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-is-generative-ai`,
      lastModified: new Date('2026-02-20'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-are-prompts`,
      lastModified: new Date('2026-02-20'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-are-ai-agents-and-permissions`,
      lastModified: new Date('2026-02-20'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-are-ai-hallucinations`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/how-to-write-a-good-prompt`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/chatgpt-vs-claude-vs-gemini`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-is-an-ai-agent`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-can-ai-agents-do-today`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-are-tokens-and-why-do-they-matter`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/is-my-data-safe-with-ai-tools`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/learn/ai-101/what-is-the-model-context-protocol`,
      lastModified: new Date('2026-02-22'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/docs`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/docs/getting-started`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/docs/consent-screen`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/docs/permissions`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/docs/action-logging`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/docs/spending-controls`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/docs/api-reference`,
      lastModified: new Date('2026-04-10'),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
  ]
}
